version: '3.4'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: web:latest
    depends_on:
      - database
      - redis
    ports:
      - "3000"
    volumes:
      - .:/web
      - gems_cache:/usr/local/bundle/gems
      - node_modules:/web/node_modules
    env_file:
      - .env
    environment:
     - NODE_ENV=production
     - WEBSOCKET_HOST=wss://footvote.xyz/api/websocket

  database:
    image: postgres:12.1
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  nginx:
    image: nginx
    links:
      - web
    volumes_from:
      - web
    volumes:
      - ./docker/development/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/development/footvote.conf:/etc/nginx/sites-enabled/footvote
    ports:
      - "80:80"
      - "443:443"

volumes:
  gems_cache:
  db_data:
  node_modules:
