version: '3.4'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
      - redis
    ports:
      - "3000"
    volumes:
      - .:/web
      - gems_cache:/usr/local/bundle/gems
      - node_modules:/web/node_modules
    env_file:
      - .env

  database:
    image: postgres:12.1
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 30

  nginx:
    image: nginx
    links:
      - web
    volumes_from:
      - web
    volumes:
      - ./docker/development/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/development/footvote.conf:/etc/nginx/sites-enabled/footvote
    ports:
      - "80:80"
      - "443:443"

  anycable:
    image: anycable/anycable-go:1.0
    command: bundle exec anycable
    env_file:
      - .env
    volumes_from:
      - web
    ports:
      - '50051'
    depends_on:
      redis:
        condition: service_healthy


volumes:
  gems_cache:
  db_data:
  node_modules:
