version: '3.4'

services:
  web_app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
      - redis
    ports:
      - "3000"
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/app/node_modules
    env_file: .env

  database:
    image: postgres:12.1
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file: .env

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  nginx:
    image: nginx
    links:
      - web_app
    volumes_from:
      - web_app
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/my_app.conf:ro
    ports:
      - "80:80"

volumes:
  gem_cache:
  db_data:
  node_modules:
