version: '3.4'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
      - redis
    ports:
      - "3000:3000"
    volumes:
      - .:/web
      - gems_cache:/usr/local/bundle/gems
      - node_modules:/web/node_modules
    env_file:
      - .env

  database:
    image: postgres:12.1
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  nginx:
    image: nginx:latest
    links:
      - web
    volumes_from:
      - web
    volumes:
      - ./docker/production/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/production/footvote.conf:/etc/nginx/sites-enabled/footvote
      - ./docker/production/fullchain.pem:/etc/nginx/fullchain.pem
      - ./docker/production/privkey.pem:/etc/nginx/privkey.pem
    ports:
      - "80:80"
      - "443:443"

volumes:
  gems_cache:
  db_data:
  node_modules:
